# Generated by Django 3.2.13 on 2022-07-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220626_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_final',
            field=models.IntegerField(null=True),
        ),
    ]
