# Generated by Django 3.2.13 on 2022-07-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripciones',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=30)),
                ('estado', models.BooleanField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
